title: Marklab Website
email: todo
description: Website of marklab

baseurl: "/marklab-website" # the subpath of your site, e.g. /blog

# Theme settings

# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
  - jekyll-remote-theme

sass:
  style: compressed

fixed_navbar: top
footer_menu: footer

collections:
  pages:
    output: true
    permalink: /:path/