title: Marklab Website
email: todo
description: Website of marklab

baseurl: "marklab-website" # the subpath of your site, e.g. /blog

# Theme settings

remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-remote-theme

